language: node_js

node_js:
- '0.12'

before_install:
- npm install hexo -g

# Decrypt the private key
- openssl aes-256-cbc -K $encrypted_112712e457d2_key -iv $encrypted_112712e457d2_iv -in .travis/gt_blog_id_rsa.enc -out ~/.ssh/gt_blog_id_rsa -d
# Set the permission of the key
- chmod 600 ~/.ssh/gt_blog_id_rsa
# Start SSH agent
- eval $(ssh-agent)
# Add the private key to the system
- ssh-add ~/.ssh/gt_blog_id_rsa
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config
# Set Git config
- git config --global user.name "travis_bot"
- git config --global user.email "wangsheng2008love@gmail.com"

script:
- hexo generate
- hexo deploy
branches:
  only:
  - blog
